name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal --logger "trx;LogFileName=test_results.trx"

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK }}

      - name: Snyk Code Analysis (SAST)
        run: snyk code test
    
      - name: Snyk Dependency Analysis (SCA)
        run: snyk test --file=SecureLens.sln

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: SecureLens.Tests/bin/Release/net8.0/test_results.trx
