name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal --logger "trx;LogFileName=test_results.trx"

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK }}

      - name: Snyk Code Analysis (SAST)
        run: snyk code test

      - name: Snyk Dependency Analysis (SCA)
        run: snyk test --file=SecureLens.sln

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: SecureLens.Tests/bin/Release/net8.0/test_results.trx

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Azure CLI Login
        env:
          AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
          AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
        run: az login -u "$AZURE_USERNAME" -p "$AZURE_PASSWORD"

      - name: Set Azure Subscription
        run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform -chdir=./infrastructure init

      - name: Terraform Plan & Apply
        env:
          TF_VAR_admin_username: ${{ secrets.TERRAFORM_ADMIN_USERNAME }}
          TF_VAR_admin_password: ${{ secrets.TERRAFORM_ADMIN_PASSWORD }}
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_source_address: ${{ secrets.AZURE_SOURCE_IP }}
          TF_VAR_domain_admin_username: ${{ secrets.TERRAFORM_DOMAIN_ADMIN_USERNAME }}
          TF_VAR_domain_admin_password: ${{ secrets.TERRAFORM_DOMAIN_ADMIN_PASSWORD }}
          TF_VAR_safe_mode_password: ${{ secrets.TERRAFORM_SAFE_MODE_PASSWORD }}
          TF_VAR_domain_name: ${{ secrets.TERRAFORM_DOMAIN_NAME }}
          TF_VAR_domain_netbios_name: ${{ secrets.TERRAFORM_DOMAIN_NETBIOS_NAME }}
          TF_VAR_user_name: ${{ secrets.TERRAFORM_TEST_USERNAME }}
          TF_VAR_user_password: ${{ secrets.TERRAFORM_TEST_PASSWORD }}
          TF_VAR_group_name: ${{ secrets.TERRAFORM_GROUP_NAME }}
        run: |
          terraform -chdir=./infrastructure plan
          terraform -chdir=./infrastructure apply -auto-approve
